[package]
name = "lithos-adapters"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
bench = false

[dependencies]
lithos-domain.workspace = true
tokio.workspace = true
serde.workspace = true
redb.workspace = true
rkyv.workspace = true
minijinja.workspace = true
pulldown-cmark.workspace = true
figment.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
miette.workspace = true
async-trait.workspace = true
chrono.workspace = true
uuid.workspace = true
toml.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
lithos-test-utils = { path = "../../tests/utils" }
proptest.workspace = true
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
