[package]
name = "trace-template"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
miette.workspace = true
serde.workspace = true
redb.workspace = true
rkyv.workspace = true
uuid.workspace = true
chrono.workspace = true
serde_json.workspace = true
toml.workspace = true
minijinja = "2.20"
base64.workspace = true
dirs.workspace = true
trace-db = { path = "../db" }
trace-support = { path = "../support" }
trace-fs = { path = "../fs" }
trace-utils = { path = "../utils" }
trace-settings = { path = "../settings" }

[lints]
workspace = true

[features]
testing = ["trace-db/testing", "trace-support/testing"]

[dev-dependencies]
pretty_assertions.workspace = true
tempfile.workspace = true
trace-db = { path = "../db", features = ["testing"] }
trace-support = { path = "../support", features = ["testing"] }
