# -----------------------------------------------------------------------------
# Filename: lithos/.gitleaks.toml
# Description: Gitleaks configuration for FlowForge secret scanning
# Documentation: https://github.com/gitleaks/gitleaks?tab=readme-ov-file#configuration
# -----------------------------------------------------------------------------

[extend]
# Use the default gitleaks configuration as a base
useDefault = true

[[rules]]
id = "aws-access-key-id"
description = "AWS Access Key ID"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
secretGroup = 1

[[rules]]
id = "aws-secret-access-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
secretGroup = 1

[[rules]]
id = "github-personal-access-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''

[[rules]]
id = "github-oauth-token"
description = "GitHub OAuth Access Token"
regex = '''gho_[0-9a-zA-Z]{36}'''

[[rules]]
id = "github-app-token"
description = "GitHub App Token"
regex = '''(ghu|ghs)_[0-9a-zA-Z]{36}'''

[[rules]]
id = "github-refresh-token"
description = "GitHub Refresh Token"
regex = '''ghr_[0-9a-zA-Z]{76}'''

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''

[[rules]]
id = "slack-webhook"
description = "Slack Webhook"
regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN[ A-Z0-9_-]*PRIVATE KEY[ A-Z0-9_-]*-----'''

[[rules]]
id = "api-key-generic"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|api-key)(.{0,20})?['\"][0-9a-zA-Z]{20,}['\"]'''

[[rules]]
id = "password-in-config"
description = "Password in Configuration"
regex = '''(?i)(password|passwd|pwd)(.{0,20})?['\"][0-9a-zA-Z!@#$%^&*()_+-=]{8,}['\"]'''

[[rules]]
id = "jwt-token"
description = "JSON Web Token"
regex = '''eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'''

[[rules]]
id = "database-connection-string"
description = "Database Connection String"
regex = '''(?i)(mongodb|mysql|postgres|postgresql)://[^\s'"]+'''

[[rules]]
id = "high-entropy-string"
description = "High Entropy String"
regex = '''[A-Za-z0-9+/]{40,}={0,2}'''
entropy = 4.5

[allowlist]
description = "Allowlist for test files and documentation"
files = [
  '''\.example$''',
  '''\.template$''',
  '''\.sample$''',
  '''^docs/''',
  '''^examples/''',
  '''_test\.go$''',
  '''test_.*\.go$''',
  '''.*_test_.*\.go$''',
]

# Allow specific patterns that are commonly used in documentation or test files
regexes = [
  '''example\.com''',
  '''localhost''',
  '''127\.0\.0\.1''',
  '''placeholder''',
  '''your-api-key-here''',
  '''INSERT_API_KEY_HERE''',
  '''TODO:''',
  '''FIXME:''',
  '''XXX:''',
]

# Allow specific known false positives
paths = [
  '''^docs/refs/''',
  '''\.gitleaks\.toml''',
  '''\.pre-commit-config\.yaml''',
  '''go\.mod''',
  '''go\.sum''',
  '''README\.md''',
]
