# -----------------------------------------------------------------------------
# Filename:    lithos/rustfmt.toml
# Docs:        https://rust-lang.github.io/rustfmt/
# Description: Configuration for rustfmt, defining code style standards such
#              as edition, line endings, and import grouping.
# -----------------------------------------------------------------------------

edition = "2021"
newline_style = "Unix"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
max_width = 100
