//! View types for schema persistence.
//!
//! This module contains view types that provide specialized representations
//! of schema data for specific use cases (staleness detection, inheritance
//! tracking).
//!
//! ## Module Structure
//!
//! - `raw` - Raw file version views (`RawSchemaView`, `RawPropertyBankView`)
//! - `inheritance` - Inheritance relationship views (`ChildSchemaView`,
//!   `ParentSchemaView`)
//! - `metadata` - Version metadata (`FileTimesMetadata`, `HashMetadata`)
//! - `version` - Versioned content (`SchemaVersion`, `PropertyBankVersion`)
//! - `file_path` - File path newtype (`FilePath`)
//!
//! ## View Pattern
//!
//! Views are optional optimizations. Only introduce them when profiling shows
//! the domain shape is inefficient for storage/queries. The `Archived*` types
//! generated by rkyv often provide sufficient zero-copy optimization.
//!
//! ## Staleness Detection
//!
//! Staleness detection is performed via metadata methods:
//! - `FileTimesMetadata::is_timestamp_match()` - Fast timestamp-only check
//! - `HashMetadata::is_content_match()` - Accurate hash-based check
//!
//! Views provide `current()` to access the most recent version.

#![expect(
    clippy::pub_use,
    reason = "Re-exports provide ergonomic API - users import from views, not \
              submodules"
)]

pub mod file_path;
pub mod inheritance;
pub mod metadata;
pub mod raw;
pub mod version;

// Re-export commonly used types for ergonomic access
pub use file_path::FilePath;
pub use inheritance::{
    ChildSchemaView, ParentSchemaView, SchemaInheritanceView,
};
pub use metadata::{FileTimesMetadata, HashMetadata};
pub use raw::{RawPropertyBankView, RawSchemaView};
pub use version::{PropertyBankVersion, SchemaVersion};
