//! View types for schema persistence.
//!
//! This module contains view types that provide specialized representations
//! of schema data for specific use cases (staleness detection, inheritance
//! tracking).
//!
//! ## Module Structure
//!
//! - `raw` - Raw file version views (`RawSchemaView`, `RawPropertyBankView`,
//!   `RawFileVersion`)
//! - `inheritance` - Inheritance relationship views (`ChildSchemaView`,
//!   `ParentSchemaView`)
//!
//! ## View Pattern
//!
//! Views are optional optimizations. Only introduce them when profiling shows
//! the domain shape is inefficient for storage/queries. The `Archived*` types
//! generated by rkyv often provide sufficient zero-copy optimization.
//!
//! ## Staleness Detection
//!
//! Staleness detection is performed via `RawFileVersion` methods:
//! - `is_timestamp_match()` - Fast timestamp-only check
//! - `is_content_match()` - Accurate hash-based check
//! - `changed_properties()` - Incremental change detection
//!
//! Views provide `current()` to access the most recent `RawFileVersion`.

#![expect(
    clippy::pub_use,
    reason = "Re-exports provide ergonomic API - users import from views, not \
              submodules"
)]

pub mod inheritance;
pub mod raw;

// Re-export commonly used types for ergonomic access
pub use inheritance::{
    ChildSchemaView, ParentSchemaView, SchemaInheritanceView,
};
pub use raw::{RawFileVersion, RawPropertyBankView, RawSchemaView};
