//! View types for schema staleness detection and version tracking.
//!
//! This module provides specialized representations of schema data for
//! staleness detection, incremental updates, and inheritance tracking.
//!
//! ## Module Structure
//!
//! - [`contracts`] - Shared traits ([`RawView`], [`RawViewRead`], [`Version`],
//!   [`VersionRead`])
//! - [`raw`] - Raw file version views ([`RawSchemaView`],
//!   [`RawPropertyBankView`])
//! - [`hashes`] - Hash records ([`HashRecord`])
//! - [`snapshots`] - Version payloads ([`SchemaVersion`],
//!   [`PropertyBankVersion`])
//!
//! ## View Pattern
//!
//! Views are optional optimizations. Only introduce them when profiling shows
//! the domain shape is inefficient for storage/queries. The `Archived*` types
//! generated by rkyv often provide sufficient zero-copy optimization.
//!
//! ## Staleness Detection
//!
//! Staleness detection is performed via metadata methods:
//! - [`FileStats::is_timestamp_match`] on each `*Version` — Fast timestamp-only
//!   check
//! - [`HashRecord::is_content_match`] — Accurate hash-based check
//!
//! Views provide [`RawView::current`] to access the most recent version.
//!
//! # Examples
//!
//! ```rust
//! # use lithos_core::schema::views::*;
//! # use lithos_core::fs::{FileStats, RelativePath};
//! # use lithos_core::support::hash::Blake3Hash;
//! # use std::time::SystemTime;
//! #
//! let path = RelativePath::try_from("schemas/note.json").unwrap();
//! let stats = FileStats::new(Some(SystemTime::now()), None, 1024);
//! let hash = Blake3Hash::compute(b"content");
//! // Use RawSchemaView for staleness detection
//! ```

#![expect(
    clippy::pub_use,
    reason = "Re-exports provide ergonomic API - users import from views, not \
              submodules"
)]

pub mod contracts;
pub mod hashes;
pub mod raw;
pub mod snapshots;

// Re-export commonly used types for ergonomic access
pub use contracts::{RawView, RawViewRead, Version, VersionRead};
pub use hashes::HashRecord;
pub use raw::{RawPropertyBankView, RawSchemaView};
pub use snapshots::{PropertyBankVersion, SchemaVersion};
