[package]
name = "lithos-domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
bench = false

[dependencies]
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
async-trait.workspace = true
chrono.workspace = true

[dev-dependencies]
lithos-test-utils = { path = "../../tests/utils" }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
mockall.workspace = true
rstest.workspace = true
proptest.workspace = true

[lints]
workspace = true
